version: '3'

services:
  web:
    build: .
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    container_name: music_service
    volumes:
      - .:/music_service
    ports:
      - "8000:8000"

    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:11
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=mutuba
      - POSTGRES_PASSWORD=''
      - POSTGRES_DB=guru99

volumes:
  postgres_data: